### ISSUE TITLE
Missing build.ninja in github clone

### ISSUE THREAD

**Issue by F3arM3** [PrimeDecomp/prime#18]
I am following the guide but when I run ninja it says "ninja: error: loading 'build.ninja': No such file or directory"

**Comment by EpochFlame** [comment]
did you run configure.py yet

**Comment by Antidote** [comment]
That's intentional, you need to run configure.py after setting up the files in orig like the readme states.

**Comment by F3arM3** [comment]
it says python command not found even though I have python installed

**Comment by Antidote** [comment]
Make sure python's bin path is in your PATH environment variable.

**Comment by F3arM3** [comment]
oh I see, I had to type "Python3 Configure.py"

**Comment by F3arM3** [comment]
now when I run ninja it says 
"[1/2] SPLIT config/GM8E01_00/config.yml
FAILED: build/GM8E01_00/config.json 
build/tools/dtk dol split config/GM8E01_00/config.yml build/GM8E01_00
 INFO Loading config/GM8E01_00/config.yml
Failed: Failed to open file 'orig/GM8E01_00/files/NESemuP.rel'

Caused by:
    No such file or directory (os error 2)
ninja: error: rebuilding 'build.ninja': subcommand failed'

**Comment by Antidote** [comment]
Please read and follow the readme step by step, all of the issues you've been running into are addressed by it.

**Comment by Antidote** [comment]
There is one step that has not been added to the readme just yet, you'll also need to run `git submodule init`

**Comment by F3arM3** [comment]
Does that have something to do with the bunch of errors I have about missing musyx files?

**Comment by Antidote** [comment]
Yes, I recently moved musyx to a submodule.

**Comment by F3arM3** [comment]
ok, now I am getting some failed processes which I copied into this text file, I even restarted the process
[Prime-error.txt](https://github.com/PrimeDecomp/prime/files/13746792/Prime-error.txt)

**Comment by Antidote** [comment]
I messed up the github command, it's actually `git submodule update --init` but if you've already run the first command just `git submodule update` should suffice.

**Comment by F3arM3** [comment]
still getting errors
[Prime-error2.txt](https://github.com/PrimeDecomp/prime/files/13746828/Prime-error2.txt)

**Comment by Antidote** [comment]
That one I have no idea what the issue is, try `rm -rf build` and retry?

That looks like a permissions issue, but it's in your home directory, so I have no idea why that's failing.

**Comment by F3arM3** [comment]
that worked, thank you

**Comment by Antidote** [comment]
np!

**Comment by F3arM3** [comment]
if you don't mind me asking, how do I run it

**Comment by Antidote** [comment]
You run it with dolphin, basically you replace sys/main.dol in an extracted version with the one built here.
